<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>routes</string>
	</array>
	<key>name</key>
	<string>Play Routes</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\A)#</string>
			<key>end</key>
			<string>\Z</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\A)(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS|-&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.httpVerb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\Z</string>
			<key>name</key>
			<string>definition.route</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=/)</string>
					<key>end</key>
					<string>\Z</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>/</string>
							<key>end</key>
							<string>\s</string>
							<key>name</key>
							<string>string</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>variable</string>
										</dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(:|[*])([a-zA-Z]+)</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>([$])([a-zA-Z]+)&lt;</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>variable</string>
										</dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword</string>
										</dict>
									</dict>
									<key>end</key>
									<string>&gt;</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>source.regexp</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=\s)[a-zA-Z]</string>
							<key>end</key>
							<string>\Z</string>
							<key>name</key>
							<string>source.scala</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.scala</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.play.routes</string>
	<key>uuid</key>
	<string>2f98fbfb-2ea7-41e1-a3e6-e15e7388e753</string>
</dict>
</plist>
